# Generated by Django 3.0.3 on 2020-05-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_auto_20200508_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(default='', upload_to='', verbose_name='DjangoBlog/images'),
        ),
    ]
